version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/babelfish_core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/babelfish_fixtures"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/babelfish_providers"
    schedule:
      interval: "weekly"
